[phases.setup]
nixPkgs = ['nodejs_20', 'npm-9_x']

[phases.install]
cmds = [
    'npm ci --legacy-peer-deps || npm install --legacy-peer-deps'
]

[phases.build]
cmds = [
    'echo "Build phase - ElizaOS DEX Agent"'
]

[start]
cmd = 'npm start' 